name: puzzle_book_workspace
publish_to: none
environment:
  sdk: ^3.5.0
workspace:
  - app
  - packages/core
  - packages/module_rebus
  - packages/module_digit_rebus
  - packages/module_domino
  - packages/module_labyrinth
  - packages/module_rebus_ui
  - packages/module_digit_rebus_ui
  - packages/module_domino_ui
  - packages/module_labyrinth_ui
  - tools/solver
