import '../../playground_game.dart';
import 'token_graph_board.dart';
import 'token_graph_state.dart';

/// Every legal slide move available in [state] on [board].
///
/// A token slides along ONE line, any distance, to a free node, and is
/// blocked if any occupied node lies between its origin and destination.
/// Moves are generated by walking outward from each free node along each
/// line it belongs to, in both directions: the first occupied node
/// encountered in a direction may slide in (everything between it and the
/// free node is free by construction, since it was the first occupied node
/// found); anything further in that direction is blocked by it, so the walk
/// stops there.
///
/// If [from] is non-null, only moves whose origin is [from] are returned.
List<PlaygroundMove> slideMoves(
  TokenGraphBoard board,
  TokenGraphState state, {
  String? from,
}) {
  final moves = <PlaygroundMove>[];

  for (final freeIndex in state.freeIndexes) {
    final freeId = board.nodeIds[freeIndex];
    for (final (lineIndex, pos) in board.lineMembershipOf(freeId)) {
      final line = board.lines[lineIndex];
      for (final direction in [-1, 1]) {
        final between = <String>[];
        var i = pos + direction;
        while (i >= 0 && i < line.length) {
          final nodeId = line[i];
          final nodeIndex = board.indexOf(nodeId);
          if (state.tokenAt(nodeIndex) == null) {
            between.add(nodeId);
            i += direction;
            continue;
          }
          // First occupied node in this direction: it may slide in. The
          // free nodes collected so far were walked from the free node
          // outward, so reversing them puts them in origin-to-destination
          // order for the emitted path.
          moves.add(PlaygroundMove([nodeId, ...between.reversed, freeId]));
          break;
        }
      }
    }
  }

  if (from == null) return moves;
  return moves.where((m) => m.from == from).toList(growable: false);
}

/// Applies [move] to [state] on [board], returning the resulting state.
///
/// Throws [ArgumentError] if [move] is not currently legal in [state].
TokenGraphState applySlide(
  TokenGraphBoard board,
  TokenGraphState state,
  PlaygroundMove move,
) {
  final legalFromOrigin = slideMoves(board, state, from: move.from);
  if (!legalFromOrigin.contains(move)) {
    throw ArgumentError(
      'slideMoves: $move is not a legal move in state $state',
    );
  }

  final tokens = List<String?>.of(state.tokens);
  final fromIndex = board.indexOf(move.from);
  final toIndex = board.indexOf(move.to);
  tokens[toIndex] = tokens[fromIndex];
  tokens[fromIndex] = null;
  return TokenGraphState(tokens);
}
